# Generated by Django 4.2.2 on 2023-07-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prefix',
            field=models.IntegerField(choices=[(1, 'นาย'), (2, 'นางสาว'), (3, 'นาง')], default=1),
        ),
    ]
