# Generated by Django 4.2.2 on 2023-07-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_student_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student', 'verbose_name_plural': 'student'},
        ),
    ]
